### PR TITLE
Fixes Datanode shows info in Sources list inconsistent with Central

### LINKED ISSUE #335: Datanode shows info in Sources list inconsistent with Central
Datanode can display info which is inconsistent with Central's data:
image
DN says that no source is published, while Central shows that all sources are published.

This happens due to silent error handling at Node side:
image

The error shouldn't be ignored - the user should be logged out instead

### PR DESCRIPTION
**Pull request by wivern**
Resolves #335

### CODE REVIEW

File: src/main/java/com/odysseusinc/arachne/datanode/controller/BaseDataSourceController.java [hunk 1]
```diff
@@ -174,12 +181,15 @@ protected BaseDataSourceController(UserService userService,
                     e.setModelType(dto.getModelType());
                 }
             });
+        } catch (RetryableException e) {
+            LogUtils.logError(LOGGER, COMMUNICATION_FAILED, e);
+            throw new ServiceNotAvailableException("Central is not available");
+        } catch (AuthenticationException e) {
```
Comment (pavgra) [inline src/main/java/com/odysseusinc/arachne/datanode/controller/BaseDataSourceController.java]: 401 from Central is not treated as auth exception:
image
